title: Bella's CS Site
description: "Class of 2025"
owner_name: iKAN2025
github_username: iKAN2025
github_repo: "bella_2025" 
baseurl: "/bella_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/iKAN2025"}
# Rotation theme
# remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/csa.md
