title: Bella's CSA Blog
description: "Class of 2025"
owner_name: Bella
github_username: iKAN2025
github_repo: "bella_2025" 
baseurl: "/bella_2025"
future: true
remote_theme: jekyll/minima/
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/iKAN2025"}
# remote_theme: 
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/csa.md
